// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void wifiConnectionStart(lv_event_t * e)
{
	// Your code here
}

void reminder_switch(lv_event_t * e)
{
	// Your code here
}


void reminderCloseBtn(lv_event_t * e)
{
	// Your code here
}

void retrywifiConn(lv_event_t * e)
{
	// Your code here
}
