// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void ui_screen_sendalertpage_screen_init(void)
{
    ui_screen_sendalertpage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_sendalertpage, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_screen_sendalertpage_panel_backpannel1 = lv_obj_create(ui_screen_sendalertpage);
    lv_obj_set_width(ui_screen_sendalertpage_panel_backpannel1, 188);
    lv_obj_set_height(ui_screen_sendalertpage_panel_backpannel1, 50);
    lv_obj_set_x(ui_screen_sendalertpage_panel_backpannel1, 2);
    lv_obj_set_y(ui_screen_sendalertpage_panel_backpannel1, -101);
    lv_obj_set_align(ui_screen_sendalertpage_panel_backpannel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_screen_sendalertpage_panel_backpannel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_screen_sendalertpage_label_back1 = lv_label_create(ui_screen_sendalertpage_panel_backpannel1);
    lv_obj_set_width(ui_screen_sendalertpage_label_back1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_screen_sendalertpage_label_back1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_screen_sendalertpage_label_back1, 10);
    lv_obj_set_y(ui_screen_sendalertpage_label_back1, 5);
    lv_obj_set_align(ui_screen_sendalertpage_label_back1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screen_sendalertpage_label_back1, "Back");

    ui_screen_sendalertpage_image_image8 = lv_image_create(ui_screen_sendalertpage_panel_backpannel1);
    lv_image_set_src(ui_screen_sendalertpage_image_image8, &ui_img_img_back_png);
    lv_obj_set_width(ui_screen_sendalertpage_image_image8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_screen_sendalertpage_image_image8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_screen_sendalertpage_image_image8, -27);
    lv_obj_set_y(ui_screen_sendalertpage_image_image8, 5);
    lv_obj_set_align(ui_screen_sendalertpage_image_image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screen_sendalertpage_image_image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_screen_sendalertpage_image_image8, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_screen_sendalertpage_label_label35 = lv_label_create(ui_screen_sendalertpage);
    lv_obj_set_width(ui_screen_sendalertpage_label_label35, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_screen_sendalertpage_label_label35, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_screen_sendalertpage_label_label35, 0);
    lv_obj_set_y(ui_screen_sendalertpage_label_label35, -63);
    lv_obj_set_align(ui_screen_sendalertpage_label_label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screen_sendalertpage_label_label35, "Send Alerts");
    lv_obj_set_style_text_color(ui_screen_sendalertpage_label_label35, lv_color_hex(0x00FF17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screen_sendalertpage_label_label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen_sendalertpage_container_container7 = lv_obj_create(ui_screen_sendalertpage);
    lv_obj_remove_style_all(ui_screen_sendalertpage_container_container7);
    lv_obj_set_width(ui_screen_sendalertpage_container_container7, 183);
    lv_obj_set_height(ui_screen_sendalertpage_container_container7, 111);
    lv_obj_set_x(ui_screen_sendalertpage_container_container7, 1);
    lv_obj_set_y(ui_screen_sendalertpage_container_container7, 9);
    lv_obj_set_align(ui_screen_sendalertpage_container_container7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screen_sendalertpage_container_container7, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_remove_flag(ui_screen_sendalertpage_container_container7,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_screen_sendalertpage_spinner_spinner2 = lv_spinner_create(ui_screen_sendalertpage_container_container7);
    // lv_spinner_set_anim_params(ui_screen_sendalertpage_spinner_spinner2, 1000, 90);
    lv_obj_set_width(ui_screen_sendalertpage_spinner_spinner2, 58);
    lv_obj_set_height(ui_screen_sendalertpage_spinner_spinner2, 61);
    lv_obj_set_x(ui_screen_sendalertpage_spinner_spinner2, 0);
    lv_obj_set_y(ui_screen_sendalertpage_spinner_spinner2, -26);
    lv_obj_set_align(ui_screen_sendalertpage_spinner_spinner2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_screen_sendalertpage_spinner_spinner2, LV_OBJ_FLAG_CLICKABLE); /// Flags

    ui_screen_sendalertpage_label_label36 = lv_label_create(ui_screen_sendalertpage_container_container7);
    lv_obj_set_width(ui_screen_sendalertpage_label_label36, 180);
    lv_obj_set_height(ui_screen_sendalertpage_label_label36, 55);
    lv_obj_set_x(ui_screen_sendalertpage_label_label36, 3);
    lv_obj_set_y(ui_screen_sendalertpage_label_label36, 35);
    lv_obj_set_align(ui_screen_sendalertpage_label_label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screen_sendalertpage_label_label36, "Sending.........");

    ui_screen_sendalertpage_container_container8 = lv_obj_create(ui_screen_sendalertpage);
    lv_obj_remove_style_all(ui_screen_sendalertpage_container_container8);
    lv_obj_set_width(ui_screen_sendalertpage_container_container8, 203);
    lv_obj_set_height(ui_screen_sendalertpage_container_container8, 168);
    lv_obj_set_x(ui_screen_sendalertpage_container_container8, 1);
    lv_obj_set_y(ui_screen_sendalertpage_container_container8, 37);
    lv_obj_set_align(ui_screen_sendalertpage_container_container8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_screen_sendalertpage_container_container8,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_screen_sendalertpage_image_image9 = lv_image_create(ui_screen_sendalertpage_container_container8);
    lv_image_set_src(ui_screen_sendalertpage_image_image9, &ui_img_notification_png);
    lv_obj_set_width(ui_screen_sendalertpage_image_image9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_screen_sendalertpage_image_image9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_screen_sendalertpage_image_image9, -3);
    lv_obj_set_y(ui_screen_sendalertpage_image_image9, -28);
    lv_obj_set_align(ui_screen_sendalertpage_image_image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screen_sendalertpage_image_image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_screen_sendalertpage_image_image9, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_screen_sendalertpage_image_image9, 450);

    ui_screen_sendalertpage_label_label37 = lv_label_create(ui_screen_sendalertpage_container_container8);
    lv_obj_set_width(ui_screen_sendalertpage_label_label37, 184);
    lv_obj_set_height(ui_screen_sendalertpage_label_label37, 19);
    lv_obj_set_x(ui_screen_sendalertpage_label_label37, -3);
    lv_obj_set_y(ui_screen_sendalertpage_label_label37, 40);
    lv_obj_set_align(ui_screen_sendalertpage_label_label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screen_sendalertpage_label_label37, "Caregiver");
    lv_obj_set_style_text_align(ui_screen_sendalertpage_label_label37, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screen_sendalertpage_label_label37, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_screen_sendalertpage_panel_backpannel1, ui_event_ui_screen_sendalertpage_panel_backpannel1, LV_EVENT_ALL,
                        NULL);

    lv_obj_add_event_cb(ui_screen_sendalertpage_image_image9, ui_event_sendalertpage_image_image9, LV_EVENT_ALL,
                        NULL);
    uic_Screen_ImageResultPage = ui_screen_sendalertpage;
}
