// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_screen__setting_screen_init(void)
{
    ui_screen__setting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen__setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen__setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen__setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__setting__panel7 = lv_obj_create(ui_screen__setting);
    lv_obj_set_width(ui_panel__setting__panel7, 273);
    lv_obj_set_height(ui_panel__setting__panel7, 58);
    lv_obj_set_x(ui_panel__setting__panel7, -1);
    lv_obj_set_y(ui_panel__setting__panel7, -141);
    lv_obj_set_align(ui_panel__setting__panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__setting__panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__setting__panel7, lv_color_hex(0x4B4343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__setting__panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__setting__panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__setting__panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__setting__label15 = lv_label_create(ui_panel__setting__panel7);
    lv_obj_set_width(ui_label__setting__label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__setting__label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__setting__label15, 1);
    lv_obj_set_y(ui_label__setting__label15, 4);
    lv_obj_set_align(ui_label__setting__label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__setting__label15, "BACK");
    lv_obj_set_style_text_color(ui_label__setting__label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__setting__label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__setting__label15, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__setting__panel6 = lv_obj_create(ui_screen__setting);
    lv_obj_set_width(ui_panel__setting__panel6, 235);
    lv_obj_set_height(ui_panel__setting__panel6, 208);
    lv_obj_set_x(ui_panel__setting__panel6, -1);
    lv_obj_set_y(ui_panel__setting__panel6, 39);
    lv_obj_set_align(ui_panel__setting__panel6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_panel__setting__panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__setting__panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__setting__panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__setting__panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__setting__panel8 = lv_obj_create(ui_panel__setting__panel6);
    lv_obj_set_width(ui_panel__setting__panel8, 200);
    lv_obj_set_height(ui_panel__setting__panel8, 50);
    lv_obj_set_x(ui_panel__setting__panel8, -3);
    lv_obj_set_y(ui_panel__setting__panel8, -70);
    lv_obj_set_align(ui_panel__setting__panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__setting__panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__setting__panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__setting__panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__setting__panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__setting__panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch__setting__switch1 = lv_switch_create(ui_panel__setting__panel8);
    lv_obj_set_width(ui_switch__setting__switch1, 111);
    lv_obj_set_height(ui_switch__setting__switch1, 24);
    lv_obj_set_x(ui_switch__setting__switch1, 33);
    lv_obj_set_y(ui_switch__setting__switch1, 1);
    lv_obj_set_align(ui_switch__setting__switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_switch__setting__switch1, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch1, lv_color_hex(0x390800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch1, lv_color_hex(0xFF2400), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_switch__setting__switch1, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_switch__setting__switch1, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_switch__setting__switch1, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_switch__setting__switch1, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_switch__setting__switch1, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_switch__setting__switch1, 5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_image__setting__image2 = lv_image_create(ui_panel__setting__panel8);
    lv_image_set_src(ui_image__setting__image2, &ui_img_mute_png);
    lv_obj_set_width(ui_image__setting__image2, 56);
    lv_obj_set_height(ui_image__setting__image2, 47);
    lv_obj_set_x(ui_image__setting__image2, -64);
    lv_obj_set_y(ui_image__setting__image2, 0);
    lv_obj_set_align(ui_image__setting__image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__setting__image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__setting__image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__setting__image4 = lv_image_create(ui_panel__setting__panel8);
    lv_image_set_src(ui_image__setting__image4, &ui_img_unmute_png);
    lv_obj_set_width(ui_image__setting__image4, 56);
    lv_obj_set_height(ui_image__setting__image4, 47);
    lv_obj_set_x(ui_image__setting__image4, -64);
    lv_obj_set_y(ui_image__setting__image4, 0);
    lv_obj_set_align(ui_image__setting__image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__setting__image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__setting__image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel__setting__panel9 = lv_obj_create(ui_panel__setting__panel6);
    lv_obj_set_width(ui_panel__setting__panel9, 200);
    lv_obj_set_height(ui_panel__setting__panel9, 50);
    lv_obj_set_x(ui_panel__setting__panel9, -3);
    lv_obj_set_y(ui_panel__setting__panel9, -17);
    lv_obj_set_align(ui_panel__setting__panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__setting__panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__setting__panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__setting__panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__setting__panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__setting__panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch__setting__switch2 = lv_switch_create(ui_panel__setting__panel9);
    lv_obj_set_width(ui_switch__setting__switch2, 111);
    lv_obj_set_height(ui_switch__setting__switch2, 24);
    lv_obj_set_x(ui_switch__setting__switch2, 33);
    lv_obj_set_y(ui_switch__setting__switch2, 1);
    lv_obj_set_align(ui_switch__setting__switch2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_switch__setting__switch2, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch2, lv_color_hex(0x390800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch2, lv_color_hex(0xFF2400), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_switch__setting__switch2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_switch__setting__switch2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_switch__setting__switch2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_switch__setting__switch2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_switch__setting__switch2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_switch__setting__switch2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_image__setting__image5 = lv_image_create(ui_panel__setting__panel9);
    lv_image_set_src(ui_image__setting__image5, &ui_img_heart_png);
    lv_obj_set_width(ui_image__setting__image5, 56);
    lv_obj_set_height(ui_image__setting__image5, 47);
    lv_obj_set_x(ui_image__setting__image5, -64);
    lv_obj_set_y(ui_image__setting__image5, 0);
    lv_obj_set_align(ui_image__setting__image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__setting__image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__setting__image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel__setting__panel11 = lv_obj_create(ui_panel__setting__panel6);
    lv_obj_set_width(ui_panel__setting__panel11, 200);
    lv_obj_set_height(ui_panel__setting__panel11, 50);
    lv_obj_set_x(ui_panel__setting__panel11, -3);
    lv_obj_set_y(ui_panel__setting__panel11, 40);
    lv_obj_set_align(ui_panel__setting__panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__setting__panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__setting__panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__setting__panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__setting__panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__setting__panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch__setting__switch4 = lv_switch_create(ui_panel__setting__panel11);
    lv_obj_set_width(ui_switch__setting__switch4, 111);
    lv_obj_set_height(ui_switch__setting__switch4, 24);
    lv_obj_set_x(ui_switch__setting__switch4, 33);
    lv_obj_set_y(ui_switch__setting__switch4, 1);
    lv_obj_set_align(ui_switch__setting__switch4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_switch__setting__switch4, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch4, lv_color_hex(0x390800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch4, lv_color_hex(0xFF2400), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_switch__setting__switch4, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_switch__setting__switch4, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_switch__setting__switch4, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_switch__setting__switch4, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_switch__setting__switch4, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_switch__setting__switch4, 5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_image__setting__image9 = lv_image_create(ui_panel__setting__panel11);
    lv_image_set_src(ui_image__setting__image9, &ui_img_step_png);
    lv_obj_set_width(ui_image__setting__image9, 56);
    lv_obj_set_height(ui_image__setting__image9, 47);
    lv_obj_set_x(ui_image__setting__image9, -64);
    lv_obj_set_y(ui_image__setting__image9, 0);
    lv_obj_set_align(ui_image__setting__image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__setting__image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__setting__image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel__setting__panel10 = lv_obj_create(ui_panel__setting__panel6);
    lv_obj_set_width(ui_panel__setting__panel10, 200);
    lv_obj_set_height(ui_panel__setting__panel10, 50);
    lv_obj_set_x(ui_panel__setting__panel10, -1);
    lv_obj_set_y(ui_panel__setting__panel10, 100);
    lv_obj_set_align(ui_panel__setting__panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__setting__panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__setting__panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__setting__panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__setting__panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__setting__panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch__setting__switch3 = lv_switch_create(ui_panel__setting__panel10);
    lv_obj_set_width(ui_switch__setting__switch3, 111);
    lv_obj_set_height(ui_switch__setting__switch3, 24);
    lv_obj_set_x(ui_switch__setting__switch3, 33);
    lv_obj_set_y(ui_switch__setting__switch3, 1);
    lv_obj_set_align(ui_switch__setting__switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_switch__setting__switch3, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch3, lv_color_hex(0x390800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch3, lv_color_hex(0xFF2400), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_switch__setting__switch3, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_switch__setting__switch3, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_switch__setting__switch3, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_switch__setting__switch3, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_switch__setting__switch3, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_switch__setting__switch3, 5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_image__setting__image7 = lv_image_create(ui_panel__setting__panel10);
    lv_image_set_src(ui_image__setting__image7, &ui_img_flash_png);
    lv_obj_set_width(ui_image__setting__image7, 56);
    lv_obj_set_height(ui_image__setting__image7, 47);
    lv_obj_set_x(ui_image__setting__image7, -64);
    lv_obj_set_y(ui_image__setting__image7, 0);
    lv_obj_set_align(ui_image__setting__image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__setting__image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__setting__image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel__setting__panel12 = lv_obj_create(ui_panel__setting__panel6);
    lv_obj_set_width(ui_panel__setting__panel12, 200);
    lv_obj_set_height(ui_panel__setting__panel12, 50);
    lv_obj_set_x(ui_panel__setting__panel12, -1);
    lv_obj_set_y(ui_panel__setting__panel12, 100);
    lv_obj_set_align(ui_panel__setting__panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__setting__panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__setting__panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__setting__panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__setting__panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__setting__panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch__setting__switch5 = lv_switch_create(ui_panel__setting__panel12);
    lv_obj_set_width(ui_switch__setting__switch5, 111);
    lv_obj_set_height(ui_switch__setting__switch5, 24);
    lv_obj_set_x(ui_switch__setting__switch5, 33);
    lv_obj_set_y(ui_switch__setting__switch5, 1);
    lv_obj_set_align(ui_switch__setting__switch5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_switch__setting__switch5, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch5, lv_color_hex(0x390800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch__setting__switch5, lv_color_hex(0xFF2400), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch__setting__switch5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_switch__setting__switch5, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_switch__setting__switch5, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_switch__setting__switch5, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_switch__setting__switch5, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_switch__setting__switch5, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_switch__setting__switch5, 5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_image__setting__image3 = lv_image_create(ui_panel__setting__panel12);
    lv_image_set_src(ui_image__setting__image3, &ui_img_flash_png);
    lv_obj_set_width(ui_image__setting__image3, 56);
    lv_obj_set_height(ui_image__setting__image3, 47);
    lv_obj_set_x(ui_image__setting__image3, -64);
    lv_obj_set_y(ui_image__setting__image3, 0);
    lv_obj_set_align(ui_image__setting__image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__setting__image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__setting__image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label__setting__label14 = lv_label_create(ui_screen__setting);
    lv_obj_set_width(ui_label__setting__label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__setting__label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__setting__label14, -38);
    lv_obj_set_y(ui_label__setting__label14, -90);
    lv_obj_set_align(ui_label__setting__label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__setting__label14, "Setting");
    lv_obj_set_style_text_color(ui_label__setting__label14, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__setting__label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label__setting__label14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_label__setting__label14, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__setting__label14, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__setting__label16 = lv_label_create(ui_screen__setting);
    lv_obj_set_width(ui_label__setting__label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__setting__label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__setting__label16, 45);
    lv_obj_set_y(ui_label__setting__label16, -90);
    lv_obj_set_align(ui_label__setting__label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__setting__label16, "Screen");
    lv_obj_set_style_text_color(ui_label__setting__label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__setting__label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__setting__label16, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_panel__setting__panel7, ui_event_panel__setting__panel7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switch__setting__switch1, ui_event_switch__setting__switch1, LV_EVENT_ALL, NULL);
    uic_Screen__setting = ui_screen__setting;

}
