// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void ui_screen_reminderpage_screen_init(void)
{
    ui_screen_reminderpage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_reminderpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_reminderpage_panel_backpannel2 = lv_obj_create(ui_screen_reminderpage);
    lv_obj_set_width(ui_reminderpage_panel_backpannel2, 188);
    lv_obj_set_height(ui_reminderpage_panel_backpannel2, 50);
    lv_obj_set_x(ui_reminderpage_panel_backpannel2, 2);
    lv_obj_set_y(ui_reminderpage_panel_backpannel2, -101);
    lv_obj_set_align(ui_reminderpage_panel_backpannel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_reminderpage_panel_backpannel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_reminderpage_label_back2 = lv_label_create(ui_reminderpage_panel_backpannel2);
    lv_obj_set_width(ui_reminderpage_label_back2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderpage_label_back2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderpage_label_back2, 10);
    lv_obj_set_y(ui_reminderpage_label_back2, 5);
    lv_obj_set_align(ui_reminderpage_label_back2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderpage_label_back2, "Back");

    ui_reminderpage_image_image3 = lv_image_create(ui_reminderpage_panel_backpannel2);
    lv_image_set_src(ui_reminderpage_image_image3, &ui_img_img_back_png);
    lv_obj_set_width(ui_reminderpage_image_image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderpage_image_image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderpage_image_image3, -27);
    lv_obj_set_y(ui_reminderpage_image_image3, 5);
    lv_obj_set_align(ui_reminderpage_image_image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_reminderpage_image_image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_reminderpage_image_image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_reminderpage_label_label7 = lv_label_create(ui_screen_reminderpage);
    lv_obj_set_width(ui_reminderpage_label_label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderpage_label_label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderpage_label_label7, 0);
    lv_obj_set_y(ui_reminderpage_label_label7, -61);
    lv_obj_set_align(ui_reminderpage_label_label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderpage_label_label7, "Reminder Page");
    lv_obj_set_style_text_color(ui_reminderpage_label_label7, lv_color_hex(0x00FF17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reminderpage_label_label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderpage_switch_switch1 = lv_switch_create(ui_screen_reminderpage);
    lv_obj_set_width(ui_reminderpage_switch_switch1, 114);
    lv_obj_set_height(ui_reminderpage_switch_switch1, 25);
    lv_obj_set_x(ui_reminderpage_switch_switch1, 0);
    lv_obj_set_y(ui_reminderpage_switch_switch1, -9);
    lv_obj_set_align(ui_reminderpage_switch_switch1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_reminderpage_panel_backpannel2, ui_event_reminderpage_panel_backpannel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_reminderpage_switch_switch1, ui_event_reminderpage_switch_switch1, LV_EVENT_ALL, NULL);

}
