// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_screen_bloodpressure_screen_init(void)
{
    ui_screen_bloodpressure = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_bloodpressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen_bloodpressure, lv_color_hex(0x010000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_bloodpressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bloodpressurepanel_bloodgroup = lv_obj_create(ui_screen_bloodpressure);
    lv_obj_set_width(ui_bloodpressurepanel_bloodgroup, 128);
    lv_obj_set_height(ui_bloodpressurepanel_bloodgroup, 131);
    lv_obj_set_x(ui_bloodpressurepanel_bloodgroup, 0);
    lv_obj_set_y(ui_bloodpressurepanel_bloodgroup, -21);
    lv_obj_set_align(ui_bloodpressurepanel_bloodgroup, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bloodpressurepanel_bloodgroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bloodpressurepanel_bloodgroup, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bloodpressurepanel_bloodgroup, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bloodpressurepanel_bloodgroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_bloodpressurepanel_bloodgroup, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_bloodpressurepanel_bloodgroup, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_bloodpressurepanel_bloodgroup, lv_color_hex(0x4E2725),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_bloodpressurepanel_bloodgroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_bloodpressurepanel_bloodgroup, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_bloodpressurepanel_bloodgroup, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bloodpressureimage_blood1 = lv_image_create(ui_bloodpressurepanel_bloodgroup);
    lv_image_set_src(ui_bloodpressureimage_blood1, &ui_img_wave2_png);
    lv_obj_set_width(ui_bloodpressureimage_blood1, 400);
    lv_obj_set_height(ui_bloodpressureimage_blood1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bloodpressureimage_blood1, -97);
    lv_obj_set_y(ui_bloodpressureimage_blood1, -6);
    lv_obj_set_align(ui_bloodpressureimage_blood1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bloodpressureimage_blood1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bloodpressureimage_blood1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_bloodpressureimage_blood1, LV_IMAGE_ALIGN_TILE);

    ui_bloodpressurepanel_bloodfill = lv_obj_create(ui_bloodpressurepanel_bloodgroup);
    lv_obj_set_height(ui_bloodpressurepanel_bloodfill, 68);
    lv_obj_set_width(ui_bloodpressurepanel_bloodfill, lv_pct(137));
    lv_obj_set_x(ui_bloodpressurepanel_bloodfill, -1);
    lv_obj_set_y(ui_bloodpressurepanel_bloodfill, 20);
    lv_obj_set_align(ui_bloodpressurepanel_bloodfill, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_bloodpressurepanel_bloodfill, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bloodpressurepanel_bloodfill, lv_color_hex(0xDE615A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bloodpressurepanel_bloodfill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_bloodpressurepanel_bloodfill, lv_color_hex(0xDE1810),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_bloodpressurepanel_bloodfill, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_bloodpressurepanel_bloodfill, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bloodpressureimage_blood3 = lv_image_create(ui_bloodpressurepanel_bloodgroup);
    lv_image_set_src(ui_bloodpressureimage_blood3, &ui_img_wave1_png);
    lv_obj_set_width(ui_bloodpressureimage_blood3, 400);
    lv_obj_set_height(ui_bloodpressureimage_blood3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bloodpressureimage_blood3, -97);
    lv_obj_set_y(ui_bloodpressureimage_blood3, -6);
    lv_obj_set_align(ui_bloodpressureimage_blood3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bloodpressureimage_blood3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bloodpressureimage_blood3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_bloodpressureimage_blood3, LV_IMAGE_ALIGN_TILE);

    ui_bloodpressurelabel_label2 = lv_label_create(ui_screen_bloodpressure);
    lv_obj_set_width(ui_bloodpressurelabel_label2, 131);
    lv_obj_set_height(ui_bloodpressurelabel_label2, 17);
    lv_obj_set_x(ui_bloodpressurelabel_label2, 3);
    lv_obj_set_y(ui_bloodpressurelabel_label2, 68);
    lv_obj_set_align(ui_bloodpressurelabel_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bloodpressurelabel_label2, "Measuring....");
    lv_obj_set_style_text_color(ui_bloodpressurelabel_label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bloodpressurelabel_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bloodpressurelabel_label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bloodpressurepanel_panel3 = lv_obj_create(ui_screen_bloodpressure);
    lv_obj_set_width(ui_bloodpressurepanel_panel3, 142);
    lv_obj_set_height(ui_bloodpressurepanel_panel3, 47);
    lv_obj_set_x(ui_bloodpressurepanel_panel3, 3);
    lv_obj_set_y(ui_bloodpressurepanel_panel3, 120);
    lv_obj_set_align(ui_bloodpressurepanel_panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bloodpressurepanel_panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bloodpressurepanel_panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bloodpressurepanel_panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bloodpressurepanel_panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bloodpressurepanel_panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bloodpressureimage_image8 = lv_image_create(ui_bloodpressurepanel_panel3);
    lv_image_set_src(ui_bloodpressureimage_image8, &ui_img_heart_png);
    lv_obj_set_width(ui_bloodpressureimage_image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bloodpressureimage_image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bloodpressureimage_image8, -47);
    lv_obj_set_y(ui_bloodpressureimage_image8, 3);
    lv_obj_set_align(ui_bloodpressureimage_image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bloodpressureimage_image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bloodpressureimage_image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bloodpressurelabel_label3 = lv_label_create(ui_bloodpressurepanel_panel3);
    lv_obj_set_width(ui_bloodpressurelabel_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bloodpressurelabel_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bloodpressurelabel_label3, 37);
    lv_obj_set_y(ui_bloodpressurelabel_label3, -5);
    lv_obj_set_align(ui_bloodpressurelabel_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bloodpressurelabel_label3, "bpm");
    lv_obj_set_style_text_color(ui_bloodpressurelabel_label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bloodpressurelabel_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bloodpressurelabel_label4 = lv_label_create(ui_bloodpressurepanel_panel3);
    lv_obj_set_width(ui_bloodpressurelabel_label4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_bloodpressurelabel_label4, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_bloodpressurelabel_label4, -8);
    lv_obj_set_y(ui_bloodpressurelabel_label4, 2);
    lv_obj_set_align(ui_bloodpressurelabel_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bloodpressurelabel_label4, "?");
    lv_obj_set_style_text_color(ui_bloodpressurelabel_label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bloodpressurelabel_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bloodpressurelabel_label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bloodpressurepanel_panel1 = lv_obj_create(ui_screen_bloodpressure);
    lv_obj_set_width(ui_bloodpressurepanel_panel1, 273);
    lv_obj_set_height(ui_bloodpressurepanel_panel1, 58);
    lv_obj_set_x(ui_bloodpressurepanel_panel1, -1);
    lv_obj_set_y(ui_bloodpressurepanel_panel1, -141);
    lv_obj_set_align(ui_bloodpressurepanel_panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bloodpressurepanel_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bloodpressurepanel_panel1, lv_color_hex(0x4B4343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bloodpressurepanel_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bloodpressurepanel_panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bloodpressurepanel_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bloodpressurelabel_label1 = lv_label_create(ui_bloodpressurepanel_panel1);
    lv_obj_set_width(ui_bloodpressurelabel_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bloodpressurelabel_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bloodpressurelabel_label1, 1);
    lv_obj_set_y(ui_bloodpressurelabel_label1, 4);
    lv_obj_set_align(ui_bloodpressurelabel_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bloodpressurelabel_label1, "BACK");
    lv_obj_set_style_text_color(ui_bloodpressurelabel_label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bloodpressurelabel_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bloodpressurelabel_label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_screen_bloodpressure, ui_event_screen_bloodpressure, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bloodpressurepanel_panel1, ui_event_screen_bloodpressure_pannel_backpannel1, LV_EVENT_ALL, NULL);

}
