// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_screen__bloodpressure_screen_init(void)
{
    ui_screen__bloodpressure = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen__bloodpressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen__bloodpressure, lv_color_hex(0x010000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen__bloodpressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__bloodpressure__bloodgroup = lv_obj_create(ui_screen__bloodpressure);
    lv_obj_set_width(ui_panel__bloodpressure__bloodgroup, 128);
    lv_obj_set_height(ui_panel__bloodpressure__bloodgroup, 131);
    lv_obj_set_x(ui_panel__bloodpressure__bloodgroup, 0);
    lv_obj_set_y(ui_panel__bloodpressure__bloodgroup, -21);
    lv_obj_set_align(ui_panel__bloodpressure__bloodgroup, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__bloodpressure__bloodgroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel__bloodpressure__bloodgroup, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel__bloodpressure__bloodgroup, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__bloodpressure__bloodgroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_panel__bloodpressure__bloodgroup, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panel__bloodpressure__bloodgroup, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_panel__bloodpressure__bloodgroup, lv_color_hex(0x4E2725),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_panel__bloodpressure__bloodgroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_panel__bloodpressure__bloodgroup, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_panel__bloodpressure__bloodgroup, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image__bloodpressure__blood1 = lv_image_create(ui_panel__bloodpressure__bloodgroup);
    lv_image_set_src(ui_image__bloodpressure__blood1, &ui_img_wave2_png);
    lv_obj_set_width(ui_image__bloodpressure__blood1, 400);
    lv_obj_set_height(ui_image__bloodpressure__blood1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image__bloodpressure__blood1, -97);
    lv_obj_set_y(ui_image__bloodpressure__blood1, -6);
    lv_obj_set_align(ui_image__bloodpressure__blood1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__bloodpressure__blood1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_image__bloodpressure__blood1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_image__bloodpressure__blood1, LV_IMAGE_ALIGN_TILE);

    ui_panel__bloodpressure__bloodfill = lv_obj_create(ui_panel__bloodpressure__bloodgroup);
    lv_obj_set_height(ui_panel__bloodpressure__bloodfill, 68);
    lv_obj_set_width(ui_panel__bloodpressure__bloodfill, lv_pct(137));
    lv_obj_set_x(ui_panel__bloodpressure__bloodfill, -1);
    lv_obj_set_y(ui_panel__bloodpressure__bloodfill, 20);
    lv_obj_set_align(ui_panel__bloodpressure__bloodfill, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_panel__bloodpressure__bloodfill, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__bloodpressure__bloodfill, lv_color_hex(0xDE615A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__bloodpressure__bloodfill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panel__bloodpressure__bloodfill, lv_color_hex(0xDE1810),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panel__bloodpressure__bloodfill, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panel__bloodpressure__bloodfill, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image__bloodpressure__blood3 = lv_image_create(ui_panel__bloodpressure__bloodgroup);
    lv_image_set_src(ui_image__bloodpressure__blood3, &ui_img_wave1_png);
    lv_obj_set_width(ui_image__bloodpressure__blood3, 400);
    lv_obj_set_height(ui_image__bloodpressure__blood3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image__bloodpressure__blood3, -97);
    lv_obj_set_y(ui_image__bloodpressure__blood3, -6);
    lv_obj_set_align(ui_image__bloodpressure__blood3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__bloodpressure__blood3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_image__bloodpressure__blood3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_image__bloodpressure__blood3, LV_IMAGE_ALIGN_TILE);

    ui_label__bloodpressure__label2 = lv_label_create(ui_screen__bloodpressure);
    lv_obj_set_width(ui_label__bloodpressure__label2, 131);
    lv_obj_set_height(ui_label__bloodpressure__label2, 17);
    lv_obj_set_x(ui_label__bloodpressure__label2, 3);
    lv_obj_set_y(ui_label__bloodpressure__label2, 68);
    lv_obj_set_align(ui_label__bloodpressure__label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__bloodpressure__label2, "Measuring....");
    lv_obj_set_style_text_color(ui_label__bloodpressure__label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__bloodpressure__label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__bloodpressure__label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__bloodpressure__panel3 = lv_obj_create(ui_screen__bloodpressure);
    lv_obj_set_width(ui_panel__bloodpressure__panel3, 142);
    lv_obj_set_height(ui_panel__bloodpressure__panel3, 47);
    lv_obj_set_x(ui_panel__bloodpressure__panel3, 3);
    lv_obj_set_y(ui_panel__bloodpressure__panel3, 120);
    lv_obj_set_align(ui_panel__bloodpressure__panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__bloodpressure__panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__bloodpressure__panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__bloodpressure__panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__bloodpressure__panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__bloodpressure__panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image__bloodpressure__image8 = lv_image_create(ui_panel__bloodpressure__panel3);
    lv_image_set_src(ui_image__bloodpressure__image8, &ui_img_heart_png);
    lv_obj_set_width(ui_image__bloodpressure__image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image__bloodpressure__image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image__bloodpressure__image8, -47);
    lv_obj_set_y(ui_image__bloodpressure__image8, 3);
    lv_obj_set_align(ui_image__bloodpressure__image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__bloodpressure__image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_image__bloodpressure__image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label__bloodpressure__label3 = lv_label_create(ui_panel__bloodpressure__panel3);
    lv_obj_set_width(ui_label__bloodpressure__label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__bloodpressure__label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__bloodpressure__label3, 37);
    lv_obj_set_y(ui_label__bloodpressure__label3, -5);
    lv_obj_set_align(ui_label__bloodpressure__label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__bloodpressure__label3, "bpm");
    lv_obj_set_style_text_color(ui_label__bloodpressure__label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__bloodpressure__label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__bloodpressure__label4 = lv_label_create(ui_panel__bloodpressure__panel3);
    lv_obj_set_width(ui_label__bloodpressure__label4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_label__bloodpressure__label4, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_label__bloodpressure__label4, -8);
    lv_obj_set_y(ui_label__bloodpressure__label4, 2);
    lv_obj_set_align(ui_label__bloodpressure__label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__bloodpressure__label4, "?");
    lv_obj_set_style_text_color(ui_label__bloodpressure__label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__bloodpressure__label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__bloodpressure__label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__bloodpressure__panel1 = lv_obj_create(ui_screen__bloodpressure);
    lv_obj_set_width(ui_panel__bloodpressure__panel1, 273);
    lv_obj_set_height(ui_panel__bloodpressure__panel1, 58);
    lv_obj_set_x(ui_panel__bloodpressure__panel1, -1);
    lv_obj_set_y(ui_panel__bloodpressure__panel1, -141);
    lv_obj_set_align(ui_panel__bloodpressure__panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__bloodpressure__panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__bloodpressure__panel1, lv_color_hex(0x4B4343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__bloodpressure__panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__bloodpressure__panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__bloodpressure__panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__bloodpressure__label1 = lv_label_create(ui_panel__bloodpressure__panel1);
    lv_obj_set_width(ui_label__bloodpressure__label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__bloodpressure__label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__bloodpressure__label1, 1);
    lv_obj_set_y(ui_label__bloodpressure__label1, 4);
    lv_obj_set_align(ui_label__bloodpressure__label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__bloodpressure__label1, "BACK");
    lv_obj_set_style_text_color(ui_label__bloodpressure__label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__bloodpressure__label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__bloodpressure__label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_screen__bloodpressure, ui_event_screen__bloodpressure, LV_EVENT_ALL, NULL);

}
