// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_screen__spo2_screen_init(void)
{
    ui_screen__spo2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen__spo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen__spo2, lv_color_hex(0x010000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen__spo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__spo2__panel2 = lv_obj_create(ui_screen__spo2);
    lv_obj_set_width(ui_panel__spo2__panel2, 142);
    lv_obj_set_height(ui_panel__spo2__panel2, 53);
    lv_obj_set_x(ui_panel__spo2__panel2, 3);
    lv_obj_set_y(ui_panel__spo2__panel2, 33);
    lv_obj_set_align(ui_panel__spo2__panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__spo2__panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__spo2__panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__spo2__panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__spo2__panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__spo2__panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image__spo2__image1 = lv_image_create(ui_panel__spo2__panel2);
    lv_image_set_src(ui_image__spo2__image1, &ui_img_heart_png);
    lv_obj_set_width(ui_image__spo2__image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image__spo2__image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image__spo2__image1, -47);
    lv_obj_set_y(ui_image__spo2__image1, 3);
    lv_obj_set_align(ui_image__spo2__image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__spo2__image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_image__spo2__image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label__spo2__label6 = lv_label_create(ui_panel__spo2__panel2);
    lv_obj_set_width(ui_label__spo2__label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__spo2__label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__spo2__label6, 37);
    lv_obj_set_y(ui_label__spo2__label6, -5);
    lv_obj_set_align(ui_label__spo2__label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label6, "bpm");
    lv_obj_set_style_text_color(ui_label__spo2__label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__spo2__label7 = lv_label_create(ui_panel__spo2__panel2);
    lv_obj_set_width(ui_label__spo2__label7, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_label__spo2__label7, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_label__spo2__label7, -8);
    lv_obj_set_y(ui_label__spo2__label7, 2);
    lv_obj_set_align(ui_label__spo2__label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label7, "?");
    lv_obj_set_style_text_color(ui_label__spo2__label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__spo2__label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__spo2__panel4 = lv_obj_create(ui_screen__spo2);
    lv_obj_set_width(ui_panel__spo2__panel4, 273);
    lv_obj_set_height(ui_panel__spo2__panel4, 58);
    lv_obj_set_x(ui_panel__spo2__panel4, -1);
    lv_obj_set_y(ui_panel__spo2__panel4, -141);
    lv_obj_set_align(ui_panel__spo2__panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__spo2__panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel__spo2__panel4, lv_color_hex(0x4B4343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__spo2__panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__spo2__panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__spo2__panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__spo2__label8 = lv_label_create(ui_panel__spo2__panel4);
    lv_obj_set_width(ui_label__spo2__label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__spo2__label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__spo2__label8, 1);
    lv_obj_set_y(ui_label__spo2__label8, 4);
    lv_obj_set_align(ui_label__spo2__label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label8, "BACK");
    lv_obj_set_style_text_color(ui_label__spo2__label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__spo2__label8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__spo2__label11 = lv_label_create(ui_screen__spo2);
    lv_obj_set_width(ui_label__spo2__label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__spo2__label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__spo2__label11, -2);
    lv_obj_set_y(ui_label__spo2__label11, -91);
    lv_obj_set_align(ui_label__spo2__label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label11, "SpO2");
    lv_obj_set_style_text_color(ui_label__spo2__label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__spo2__label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__spo2__label9 = lv_label_create(ui_screen__spo2);
    lv_obj_set_width(ui_label__spo2__label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__spo2__label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__spo2__label9, 1);
    lv_obj_set_y(ui_label__spo2__label9, -69);
    lv_obj_set_align(ui_label__spo2__label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label9, "Blood Oygen");
    lv_obj_set_style_text_color(ui_label__spo2__label9, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__spo2__label10 = lv_label_create(ui_screen__spo2);
    lv_obj_set_width(ui_label__spo2__label10, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_label__spo2__label10, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_label__spo2__label10, -10);
    lv_obj_set_y(ui_label__spo2__label10, -22);
    lv_obj_set_align(ui_label__spo2__label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label10, "91");
    lv_obj_set_style_text_color(ui_label__spo2__label10, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label__spo2__label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__spo2__label10, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__spo2__label12 = lv_label_create(ui_screen__spo2);
    lv_obj_set_width(ui_label__spo2__label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__spo2__label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__spo2__label12, 29);
    lv_obj_set_y(ui_label__spo2__label12, -17);
    lv_obj_set_align(ui_label__spo2__label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label12, "%");
    lv_obj_set_style_text_color(ui_label__spo2__label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label__spo2__label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label__spo2__label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__spo2__label13 = lv_label_create(ui_screen__spo2);
    lv_obj_set_width(ui_label__spo2__label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__spo2__label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__spo2__label13, -2);
    lv_obj_set_y(ui_label__spo2__label13, -2);
    lv_obj_set_align(ui_label__spo2__label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label13, "_________________");
    lv_obj_set_style_text_color(ui_label__spo2__label13, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__spo2__label5 = lv_label_create(ui_screen__spo2);
    lv_obj_set_width(ui_label__spo2__label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__spo2__label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label__spo2__label5, 0);
    lv_obj_set_y(ui_label__spo2__label5, 55);
    lv_obj_set_align(ui_label__spo2__label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label__spo2__label5, "__________________");
    lv_obj_set_style_text_color(ui_label__spo2__label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__spo2__label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel__spo2__panel5 = lv_obj_create(ui_screen__spo2);
    lv_obj_set_width(ui_panel__spo2__panel5, 61);
    lv_obj_set_height(ui_panel__spo2__panel5, 66);
    lv_obj_set_x(ui_panel__spo2__panel5, -3);
    lv_obj_set_y(ui_panel__spo2__panel5, 105);
    lv_obj_set_align(ui_panel__spo2__panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel__spo2__panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel__spo2__panel5, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel__spo2__panel5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel__spo2__panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel__spo2__panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel__spo2__panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgbutton__spo2__imgbutton1 = lv_imagebutton_create(ui_panel__spo2__panel5);
    lv_imagebutton_set_src(ui_imgbutton__spo2__imgbutton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_measure_png, NULL);
    lv_obj_set_width(ui_imgbutton__spo2__imgbutton1, 35);
    lv_obj_set_height(ui_imgbutton__spo2__imgbutton1, 35);
    lv_obj_set_x(ui_imgbutton__spo2__imgbutton1, -2);
    lv_obj_set_y(ui_imgbutton__spo2__imgbutton1, -1);
    lv_obj_set_align(ui_imgbutton__spo2__imgbutton1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_panel__spo2__panel4, ui_event_panel__spo2__panel4, LV_EVENT_ALL, NULL);
    uic_Screen__spo2 = ui_screen__spo2;

}
