// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void ui_screen_alertpage_screen_init(void)
{
    ui_screen_alertpage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_alertpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alertpage_panel_backpannel3 = lv_obj_create(ui_screen_alertpage);
    lv_obj_set_width(ui_alertpage_panel_backpannel3, 188);
    lv_obj_set_height(ui_alertpage_panel_backpannel3, 50);
    lv_obj_set_x(ui_alertpage_panel_backpannel3, 2);
    lv_obj_set_y(ui_alertpage_panel_backpannel3, -101);
    lv_obj_set_align(ui_alertpage_panel_backpannel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_alertpage_panel_backpannel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alertpage_label_back3 = lv_label_create(ui_alertpage_panel_backpannel3);
    lv_obj_set_width(ui_alertpage_label_back3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alertpage_label_back3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alertpage_label_back3, 10);
    lv_obj_set_y(ui_alertpage_label_back3, 5);
    lv_obj_set_align(ui_alertpage_label_back3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alertpage_label_back3, "Back");

    ui_alertpage_image_image4 = lv_image_create(ui_alertpage_panel_backpannel3);
    lv_image_set_src(ui_alertpage_image_image4, &ui_img_img_back_png);
    lv_obj_set_width(ui_alertpage_image_image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alertpage_image_image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alertpage_image_image4, -27);
    lv_obj_set_y(ui_alertpage_image_image4, 5);
    lv_obj_set_align(ui_alertpage_image_image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alertpage_image_image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_alertpage_image_image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alertpage_label_label8 = lv_label_create(ui_screen_alertpage);
    lv_obj_set_width(ui_alertpage_label_label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alertpage_label_label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alertpage_label_label8, 0);
    lv_obj_set_y(ui_alertpage_label_label8, -61);
    lv_obj_set_align(ui_alertpage_label_label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alertpage_label_label8, "Alert Page");
    lv_obj_set_style_text_color(ui_alertpage_label_label8, lv_color_hex(0x00FF17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alertpage_label_label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_alertpage_panel_backpannel3, ui_event_alertpage_panel_backpannel3, LV_EVENT_ALL, NULL);

}
