// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_screen_spo2_screen_init(void)
{
    ui_screen_spo2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_spo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen_spo2, lv_color_hex(0x010000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_spo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2panel_panel2 = lv_obj_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2panel_panel2, 142);
    lv_obj_set_height(ui_spo2panel_panel2, 53);
    lv_obj_set_x(ui_spo2panel_panel2, 3);
    lv_obj_set_y(ui_spo2panel_panel2, 33);
    lv_obj_set_align(ui_spo2panel_panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_spo2panel_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_spo2panel_panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_spo2panel_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_spo2panel_panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_spo2panel_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2image_image1 = lv_image_create(ui_spo2panel_panel2);
    lv_image_set_src(ui_spo2image_image1, &ui_img_heart_png);
    lv_obj_set_width(ui_spo2image_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2image_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2image_image1, -47);
    lv_obj_set_y(ui_spo2image_image1, 3);
    lv_obj_set_align(ui_spo2image_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_spo2image_image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_spo2image_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_spo2label_label6 = lv_label_create(ui_spo2panel_panel2);
    lv_obj_set_width(ui_spo2label_label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2label_label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2label_label6, 37);
    lv_obj_set_y(ui_spo2label_label6, -5);
    lv_obj_set_align(ui_spo2label_label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label6, "bpm");
    lv_obj_set_style_text_color(ui_spo2label_label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2label_label7 = lv_label_create(ui_spo2panel_panel2);
    lv_obj_set_width(ui_spo2label_label7, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_spo2label_label7, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_spo2label_label7, -8);
    lv_obj_set_y(ui_spo2label_label7, 2);
    lv_obj_set_align(ui_spo2label_label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label7, "?");
    lv_obj_set_style_text_color(ui_spo2label_label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spo2label_label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2panel_panel4 = lv_obj_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2panel_panel4, 273);
    lv_obj_set_height(ui_spo2panel_panel4, 58);
    lv_obj_set_x(ui_spo2panel_panel4, -1);
    lv_obj_set_y(ui_spo2panel_panel4, -141);
    lv_obj_set_align(ui_spo2panel_panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_spo2panel_panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_spo2panel_panel4, lv_color_hex(0x4B4343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_spo2panel_panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_spo2panel_panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_spo2panel_panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2label_label8 = lv_label_create(ui_spo2panel_panel4);
    lv_obj_set_width(ui_spo2label_label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2label_label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2label_label8, 1);
    lv_obj_set_y(ui_spo2label_label8, 4);
    lv_obj_set_align(ui_spo2label_label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label8, "BACK");
    lv_obj_set_style_text_color(ui_spo2label_label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spo2label_label8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2label_label11 = lv_label_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2label_label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2label_label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2label_label11, -2);
    lv_obj_set_y(ui_spo2label_label11, -91);
    lv_obj_set_align(ui_spo2label_label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label11, "SpO2");
    lv_obj_set_style_text_color(ui_spo2label_label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spo2label_label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2label_label9 = lv_label_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2label_label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2label_label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2label_label9, 1);
    lv_obj_set_y(ui_spo2label_label9, -69);
    lv_obj_set_align(ui_spo2label_label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label9, "Blood Oygen");
    lv_obj_set_style_text_color(ui_spo2label_label9, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2label_label10 = lv_label_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2label_label10, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_spo2label_label10, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_spo2label_label10, -10);
    lv_obj_set_y(ui_spo2label_label10, -22);
    lv_obj_set_align(ui_spo2label_label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label10, "91");
    lv_obj_set_style_text_color(ui_spo2label_label10, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_spo2label_label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spo2label_label10, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2label_label12 = lv_label_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2label_label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2label_label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2label_label12, 29);
    lv_obj_set_y(ui_spo2label_label12, -17);
    lv_obj_set_align(ui_spo2label_label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label12, "%");
    lv_obj_set_style_text_color(ui_spo2label_label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_spo2label_label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spo2label_label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2label_label13 = lv_label_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2label_label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2label_label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2label_label13, -2);
    lv_obj_set_y(ui_spo2label_label13, -2);
    lv_obj_set_align(ui_spo2label_label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label13, "_________________");
    lv_obj_set_style_text_color(ui_spo2label_label13, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2label_label5 = lv_label_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2label_label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2label_label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2label_label5, 0);
    lv_obj_set_y(ui_spo2label_label5, 55);
    lv_obj_set_align(ui_spo2label_label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2label_label5, "__________________");
    lv_obj_set_style_text_color(ui_spo2label_label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2label_label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2panel_panel5 = lv_obj_create(ui_screen_spo2);
    lv_obj_set_width(ui_spo2panel_panel5, 61);
    lv_obj_set_height(ui_spo2panel_panel5, 66);
    lv_obj_set_x(ui_spo2panel_panel5, -3);
    lv_obj_set_y(ui_spo2panel_panel5, 105);
    lv_obj_set_align(ui_spo2panel_panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_spo2panel_panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_spo2panel_panel5, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_spo2panel_panel5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_spo2panel_panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_spo2panel_panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_spo2panel_panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2imgbutton_imgbutton1 = lv_imagebutton_create(ui_spo2panel_panel5);
    lv_imagebutton_set_src(ui_spo2imgbutton_imgbutton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_measure_png, NULL);
    lv_obj_set_width(ui_spo2imgbutton_imgbutton1, 35);
    lv_obj_set_height(ui_spo2imgbutton_imgbutton1, 35);
    lv_obj_set_x(ui_spo2imgbutton_imgbutton1, -2);
    lv_obj_set_y(ui_spo2imgbutton_imgbutton1, -1);
    lv_obj_set_align(ui_spo2imgbutton_imgbutton1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_spo2panel_panel4, ui_event_spo2panel_panel4, LV_EVENT_ALL, NULL);
    uic_Screen_spo2 = ui_screen_spo2;

}
