// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void ui_screen_reminderalert_screen_init(void)
{
    ui_screen_reminderalert = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_reminderalert, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_reminderalert_label_label26 = lv_label_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_label_label26, 78);
    lv_obj_set_height(ui_reminderalert_label_label26, 18);
    lv_obj_set_x(ui_reminderalert_label_label26, 22);
    lv_obj_set_y(ui_reminderalert_label_label26, -120);
    lv_obj_set_align(ui_reminderalert_label_label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_label26, "Reminder");
    lv_obj_set_style_text_color(ui_reminderalert_label_label26, lv_color_hex(0x0FFF56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reminderalert_label_label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_reminderalert_label_label26, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_reminderalert_label_label26, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_image_image7 = lv_image_create(ui_screen_reminderalert);
    lv_image_set_src(ui_reminderalert_image_image7, &ui_img_notification_png);
    lv_obj_set_width(ui_reminderalert_image_image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderalert_image_image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderalert_image_image7, -44);
    lv_obj_set_y(ui_reminderalert_image_image7, -121);
    lv_obj_set_align(ui_reminderalert_image_image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_reminderalert_image_image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_reminderalert_image_image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_reminderalert_image_image7, 120);

    ui_reminderalert_button_reminderbtn = lv_button_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_button_reminderbtn, 82);
    lv_obj_set_height(ui_reminderalert_button_reminderbtn, 23);
    lv_obj_set_x(ui_reminderalert_button_reminderbtn, -6);
    lv_obj_set_y(ui_reminderalert_button_reminderbtn, 127);
    lv_obj_set_align(ui_reminderalert_button_reminderbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_reminderalert_button_reminderbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_reminderalert_button_reminderbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_reminderalert_button_reminderbtn, lv_color_hex(0x24D858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_reminderalert_button_reminderbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_label_reminderbtnlabel = lv_label_create(ui_reminderalert_button_reminderbtn);
    lv_obj_set_width(ui_reminderalert_label_reminderbtnlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderalert_label_reminderbtnlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderalert_label_reminderbtnlabel, 0);
    lv_obj_set_y(ui_reminderalert_label_reminderbtnlabel, 1);
    lv_obj_set_align(ui_reminderalert_label_reminderbtnlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_reminderbtnlabel, "Close");
    lv_obj_set_style_text_font(ui_reminderalert_label_reminderbtnlabel, &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_label_label28 = lv_label_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_label_label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderalert_label_label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderalert_label_label28, -92);
    lv_obj_set_y(ui_reminderalert_label_label28, -66);
    lv_obj_set_align(ui_reminderalert_label_label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_label28, "Title :");
    lv_obj_set_style_text_color(ui_reminderalert_label_label28, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reminderalert_label_label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_label_label29 = lv_label_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_label_label29, 141);
    lv_obj_set_height(ui_reminderalert_label_label29, 31);
    lv_obj_set_x(ui_reminderalert_label_label29, 25);
    lv_obj_set_y(ui_reminderalert_label_label29, -67);
    lv_obj_set_align(ui_reminderalert_label_label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_label29, "USE MOBILE SMRITI APP");
    lv_obj_set_scroll_dir(ui_reminderalert_label_label29, LV_DIR_HOR);
    lv_obj_set_style_text_align(ui_reminderalert_label_label29, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_label_time2 = lv_label_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_label_time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderalert_label_time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderalert_label_time2, -28);
    lv_obj_set_y(ui_reminderalert_label_time2, -30);
    lv_obj_set_align(ui_reminderalert_label_time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_time2, "12:23");
    lv_obj_set_style_text_color(ui_reminderalert_label_time2, lv_color_hex(0x00FF0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reminderalert_label_time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_reminderalert_label_time2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_label_date2 = lv_label_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_label_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderalert_label_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderalert_label_date2, -2);
    lv_obj_set_y(ui_reminderalert_label_date2, -3);
    lv_obj_set_align(ui_reminderalert_label_date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_date2, "22 May 2025");
    lv_obj_set_style_text_color(ui_reminderalert_label_date2, lv_color_hex(0x00FF44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reminderalert_label_date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_label_label30 = lv_label_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_label_label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminderalert_label_label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminderalert_label_label30, 19);
    lv_obj_set_y(ui_reminderalert_label_label30, -30);
    lv_obj_set_align(ui_reminderalert_label_label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_label30, "Daily");
    lv_obj_set_style_text_color(ui_reminderalert_label_label30, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reminderalert_label_label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_reminderalert_label_label30, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_reminderalert_label_label30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_label_label31 = lv_label_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_label_label31, 88);
    lv_obj_set_height(ui_reminderalert_label_label31, 32);
    lv_obj_set_x(ui_reminderalert_label_label31, -71);
    lv_obj_set_y(ui_reminderalert_label_label31, 39);
    lv_obj_set_align(ui_reminderalert_label_label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_label31, "Description:");
    lv_obj_set_style_text_color(ui_reminderalert_label_label31, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reminderalert_label_label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_reminderalert_label_label31, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reminderalert_panel_panel4 = lv_obj_create(ui_screen_reminderalert);
    lv_obj_set_width(ui_reminderalert_panel_panel4, 143);
    lv_obj_set_height(ui_reminderalert_panel_panel4, 107);
    lv_obj_set_x(ui_reminderalert_panel_panel4, 29);
    lv_obj_set_y(ui_reminderalert_panel_panel4, 68);
    lv_obj_set_align(ui_reminderalert_panel_panel4, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_reminderalert_panel_panel4, LV_DIR_VER);
    lv_obj_set_style_radius(ui_reminderalert_panel_panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_reminderalert_panel_panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_reminderalert_panel_panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_reminderalert_panel_panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_reminderalert_panel_panel4, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_reminderalert_panel_panel4, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_reminderalert_panel_panel4, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_reminderalert_panel_panel4, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_reminderalert_label_label33 = lv_label_create(ui_reminderalert_panel_panel4);
    lv_obj_set_width(ui_reminderalert_label_label33, 123);
    lv_obj_set_height(ui_reminderalert_label_label33, 162);
    lv_obj_set_x(ui_reminderalert_label_label33, -2);
    lv_obj_set_y(ui_reminderalert_label_label33, 34);
    lv_obj_set_align(ui_reminderalert_label_label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reminderalert_label_label33, "Play Mind Game in Smriti Mobile App");

    lv_obj_add_event_cb(ui_reminderalert_button_reminderbtn, ui_event_reminderalert_button_reminderbtn, LV_EVENT_ALL, NULL);

}
