// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void ui_screen_audiocapturepage_screen_init(void)
{
    ui_screen_audiocapturepage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_audiocapturepage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_audiocapturepage_panel_backpannel6 = lv_obj_create(ui_screen_audiocapturepage);
    lv_obj_set_width(ui_audiocapturepage_panel_backpannel6, 222);
    lv_obj_set_height(ui_audiocapturepage_panel_backpannel6, 50);
    lv_obj_set_x(ui_audiocapturepage_panel_backpannel6, 0);
    lv_obj_set_y(ui_audiocapturepage_panel_backpannel6, -127);
    lv_obj_set_align(ui_audiocapturepage_panel_backpannel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_audiocapturepage_panel_backpannel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_audiocapturepage_label_back6 = lv_label_create(ui_audiocapturepage_panel_backpannel6);
    lv_obj_set_width(ui_audiocapturepage_label_back6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_audiocapturepage_label_back6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_audiocapturepage_label_back6, 10);
    lv_obj_set_y(ui_audiocapturepage_label_back6, 5);
    lv_obj_set_align(ui_audiocapturepage_label_back6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_audiocapturepage_label_back6, "Back");

    ui_audiocapturepage_image_image10 = lv_image_create(ui_audiocapturepage_panel_backpannel6);
    lv_image_set_src(ui_audiocapturepage_image_image10, &ui_img_img_back_png);
    lv_obj_set_width(ui_audiocapturepage_image_image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_audiocapturepage_image_image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_audiocapturepage_image_image10, -27);
    lv_obj_set_y(ui_audiocapturepage_image_image10, 5);
    lv_obj_set_align(ui_audiocapturepage_image_image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_audiocapturepage_image_image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_audiocapturepage_image_image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_audiocapturepage_label_label38 = lv_label_create(ui_screen_audiocapturepage);
    lv_obj_set_width(ui_audiocapturepage_label_label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_audiocapturepage_label_label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_audiocapturepage_label_label38, -3);
    lv_obj_set_y(ui_audiocapturepage_label_label38, -75);
    lv_obj_set_align(ui_audiocapturepage_label_label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_audiocapturepage_label_label38, "Capture Audio");
    lv_obj_set_style_text_color(ui_audiocapturepage_label_label38, lv_color_hex(0x00FF17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_audiocapturepage_label_label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_audiocapturepage_label_label38, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_audiocapturepage_container_container9 = lv_obj_create(ui_screen_audiocapturepage);
    lv_obj_remove_style_all(ui_audiocapturepage_container_container9);
    lv_obj_set_width(ui_audiocapturepage_container_container9, 183);
    lv_obj_set_height(ui_audiocapturepage_container_container9, 111);
    lv_obj_set_x(ui_audiocapturepage_container_container9, 1);
    lv_obj_set_y(ui_audiocapturepage_container_container9, 9);
    lv_obj_set_align(ui_audiocapturepage_container_container9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_audiocapturepage_container_container9, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_audiocapturepage_container_container9,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_audiocapturepage_spinner_spinner3 = lv_spinner_create(ui_audiocapturepage_container_container9);
    //lv_spinner_set_anim_params(ui_audiocapturepage_spinner_spinner3, 1000, 90);
    lv_obj_set_width(ui_audiocapturepage_spinner_spinner3, 58);
    lv_obj_set_height(ui_audiocapturepage_spinner_spinner3, 61);
    lv_obj_set_x(ui_audiocapturepage_spinner_spinner3, 0);
    lv_obj_set_y(ui_audiocapturepage_spinner_spinner3, -26);
    lv_obj_set_align(ui_audiocapturepage_spinner_spinner3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_audiocapturepage_spinner_spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_audiocapturepage_label_label39 = lv_label_create(ui_audiocapturepage_container_container9);
    lv_obj_set_width(ui_audiocapturepage_label_label39, 180);
    lv_obj_set_height(ui_audiocapturepage_label_label39, 55);
    lv_obj_set_x(ui_audiocapturepage_label_label39, 3);
    lv_obj_set_y(ui_audiocapturepage_label_label39, 35);
    lv_obj_set_align(ui_audiocapturepage_label_label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_audiocapturepage_label_label39, "y56y56y56y56y56y56y56y56y56y56y56y56y56y56y56y");

    ui_audiocapturepage_container_container10 = lv_obj_create(ui_screen_audiocapturepage);
    lv_obj_remove_style_all(ui_audiocapturepage_container_container10);
    lv_obj_set_width(ui_audiocapturepage_container_container10, 203);
    lv_obj_set_height(ui_audiocapturepage_container_container10, 123);
    lv_obj_set_x(ui_audiocapturepage_container_container10, 1);
    lv_obj_set_y(ui_audiocapturepage_container_container10, 10);
    lv_obj_set_align(ui_audiocapturepage_container_container10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_audiocapturepage_container_container10,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_audiocapturepage_image_image11 = lv_image_create(ui_audiocapturepage_container_container10);
    lv_image_set_src(ui_audiocapturepage_image_image11, &ui_img_voice_png);
    lv_obj_set_width(ui_audiocapturepage_image_image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_audiocapturepage_image_image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_audiocapturepage_image_image11, -5);
    lv_obj_set_y(ui_audiocapturepage_image_image11, -10);
    lv_obj_set_align(ui_audiocapturepage_image_image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_audiocapturepage_image_image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_audiocapturepage_image_image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_audiocapturepage_image_image11, 136);

    ui_audiocapturepage_label_label40 = lv_label_create(ui_audiocapturepage_container_container10);
    lv_obj_set_width(ui_audiocapturepage_label_label40, 184);
    lv_obj_set_height(ui_audiocapturepage_label_label40, 17);
    lv_obj_set_x(ui_audiocapturepage_label_label40, 8);
    lv_obj_set_y(ui_audiocapturepage_label_label40, 44);
    lv_obj_set_align(ui_audiocapturepage_label_label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_audiocapturepage_label_label40, "Recording.....");
    lv_obj_set_style_text_align(ui_audiocapturepage_label_label40, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_audiocapturepage_label_label40, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_audiocapturepage_button_button12 = lv_button_create(ui_screen_audiocapturepage);
    lv_obj_set_width(ui_audiocapturepage_button_button12, 161);
    lv_obj_set_height(ui_audiocapturepage_button_button12, 23);
    lv_obj_set_x(ui_audiocapturepage_button_button12, 0);
    lv_obj_set_y(ui_audiocapturepage_button_button12, 108);
    lv_obj_set_align(ui_audiocapturepage_button_button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_audiocapturepage_button_button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_audiocapturepage_button_button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_audiocapturepage_button_button12, lv_color_hex(0x00C124), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_audiocapturepage_button_button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_audiocapturepage_label_label42 = lv_label_create(ui_audiocapturepage_button_button12);
    lv_obj_set_width(ui_audiocapturepage_label_label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_audiocapturepage_label_label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_audiocapturepage_label_label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_audiocapturepage_label_label42, "Get Result");

    lv_obj_add_event_cb(ui_audiocapturepage_panel_backpannel6, ui_event_audiocapturepage_panel_backpannel6, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_audiocapturepage_button_button12, ui_event_audiocapturepage_button_button12, LV_EVENT_ALL, NULL);

}
