// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void ui_screen_profilepage_screen_init(void)
{
    ui_screen_profilepage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_profilepage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_panel_backpannel4 = lv_obj_create(ui_screen_profilepage);
    lv_obj_set_width(ui_profilepage_panel_backpannel4, 216);
    lv_obj_set_height(ui_profilepage_panel_backpannel4, 50);
    lv_obj_set_x(ui_profilepage_panel_backpannel4, -1);
    lv_obj_set_y(ui_profilepage_panel_backpannel4, -127);
    lv_obj_set_align(ui_profilepage_panel_backpannel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_profilepage_panel_backpannel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_label_back4 = lv_label_create(ui_profilepage_panel_backpannel4);
    lv_obj_set_width(ui_profilepage_label_back4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_back4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_back4, 11);
    lv_obj_set_y(ui_profilepage_label_back4, 1);
    lv_obj_set_align(ui_profilepage_label_back4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_back4, "Back");

    ui_profilepage_image_image5 = lv_image_create(ui_profilepage_panel_backpannel4);
    lv_image_set_src(ui_profilepage_image_image5, &ui_img_img_back_png);
    lv_obj_set_width(ui_profilepage_image_image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_image_image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_image_image5, -28);
    lv_obj_set_y(ui_profilepage_image_image5, 1);
    lv_obj_set_align(ui_profilepage_image_image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_profilepage_image_image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_profilepage_image_image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_label_label9 = lv_label_create(ui_screen_profilepage);
    lv_obj_set_width(ui_profilepage_label_label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label9, 2);
    lv_obj_set_y(ui_profilepage_label_label9, -76);
    lv_obj_set_align(ui_profilepage_label_label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label9, "Profile Page");
    lv_obj_set_style_text_color(ui_profilepage_label_label9, lv_color_hex(0x00FF17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_profilepage_label_label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_profilepage_label_label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_profilepage_container_container6 = lv_obj_create(ui_screen_profilepage);
    lv_obj_remove_style_all(ui_profilepage_container_container6);
    lv_obj_set_width(ui_profilepage_container_container6, 183);
    lv_obj_set_height(ui_profilepage_container_container6, 111);
    lv_obj_set_x(ui_profilepage_container_container6, 1);
    lv_obj_set_y(ui_profilepage_container_container6, 9);
    lv_obj_set_align(ui_profilepage_container_container6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_profilepage_container_container6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_profilepage_container_container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_spinner_spinner1 = lv_spinner_create(ui_profilepage_container_container6);
    //lv_spinner_set_anim_params(ui_profilepage_spinner_spinner1, 1000, 90);
    lv_obj_set_width(ui_profilepage_spinner_spinner1, 58);
    lv_obj_set_height(ui_profilepage_spinner_spinner1, 61);
    lv_obj_set_x(ui_profilepage_spinner_spinner1, 0);
    lv_obj_set_y(ui_profilepage_spinner_spinner1, -26);
    lv_obj_set_align(ui_profilepage_spinner_spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_profilepage_spinner_spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_profilepage_label_label24 = lv_label_create(ui_profilepage_container_container6);
    lv_obj_set_width(ui_profilepage_label_label24, 180);
    lv_obj_set_height(ui_profilepage_label_label24, 55);
    lv_obj_set_x(ui_profilepage_label_label24, 3);
    lv_obj_set_y(ui_profilepage_label_label24, 35);
    lv_obj_set_align(ui_profilepage_label_label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label24, "y56y56y56y56y56y56y56y56y56y56y56y56y56y56y56y");

    ui_profilepage_container_container5 = lv_obj_create(ui_screen_profilepage);
    lv_obj_remove_style_all(ui_profilepage_container_container5);
    lv_obj_set_width(ui_profilepage_container_container5, 203);
    lv_obj_set_height(ui_profilepage_container_container5, 120);
    lv_obj_set_x(ui_profilepage_container_container5, 0);
    lv_obj_set_y(ui_profilepage_container_container5, 7);
    lv_obj_set_align(ui_profilepage_container_container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_profilepage_container_container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_container_container1 = lv_obj_create(ui_profilepage_container_container5);
    lv_obj_remove_style_all(ui_profilepage_container_container1);
    lv_obj_set_width(ui_profilepage_container_container1, 121);
    lv_obj_set_height(ui_profilepage_container_container1, 98);
    lv_obj_set_x(ui_profilepage_container_container1, 37);
    lv_obj_set_y(ui_profilepage_container_container1, -1);
    lv_obj_set_align(ui_profilepage_container_container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_profilepage_container_container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_label_label15 = lv_label_create(ui_profilepage_container_container1);
    lv_obj_set_width(ui_profilepage_label_label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label15, -25);
    lv_obj_set_y(ui_profilepage_label_label15, 3);
    lv_obj_set_align(ui_profilepage_label_label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label15, "Device ID:");

    ui_profilepage_label_label16 = lv_label_create(ui_profilepage_container_container1);
    lv_obj_set_width(ui_profilepage_label_label16, 83);
    lv_obj_set_height(ui_profilepage_label_label16, 32);
    lv_obj_set_x(ui_profilepage_label_label16, 35);
    lv_obj_set_y(ui_profilepage_label_label16, -33);
    lv_obj_set_align(ui_profilepage_label_label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label16, "Mukul Dahiya");

    ui_profilepage_label_label17 = lv_label_create(ui_profilepage_container_container1);
    lv_obj_set_width(ui_profilepage_label_label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label17, -35);
    lv_obj_set_y(ui_profilepage_label_label17, -41);
    lv_obj_set_align(ui_profilepage_label_label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label17, "Name: ");

    ui_profilepage_label_label18 = lv_label_create(ui_profilepage_container_container1);
    lv_obj_set_width(ui_profilepage_label_label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label18, 36);
    lv_obj_set_y(ui_profilepage_label_label18, 2);
    lv_obj_set_align(ui_profilepage_label_label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label18, "2231");

    ui_profilepage_label_label46 = lv_label_create(ui_profilepage_container_container5);
    lv_obj_set_width(ui_profilepage_label_label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label46, 38);
    lv_obj_set_y(ui_profilepage_label_label46, 30);
    lv_obj_set_align(ui_profilepage_label_label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label46, "Caregiver : Pooja");

    ui_profilepage_image_image2 = lv_image_create(ui_profilepage_container_container5);
    lv_image_set_src(ui_profilepage_image_image2, &ui_img_mukul_pic_png);
    lv_obj_set_width(ui_profilepage_image_image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_image_image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_image_image2, -68);
    lv_obj_set_y(ui_profilepage_image_image2, -19);
    lv_obj_set_align(ui_profilepage_image_image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_profilepage_image_image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_profilepage_image_image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_label_label45 = lv_label_create(ui_profilepage_container_container5);
    lv_obj_set_width(ui_profilepage_label_label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label45, -70);
    lv_obj_set_y(ui_profilepage_label_label45, 31);
    lv_obj_set_align(ui_profilepage_label_label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label45, "Age : 35");

    ui_profilepage_label_label47 = lv_label_create(ui_screen_profilepage);
    lv_obj_set_width(ui_profilepage_label_label47, 183);
    lv_obj_set_height(ui_profilepage_label_label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label47, -8);
    lv_obj_set_y(ui_profilepage_label_label47, 69);
    lv_obj_set_align(ui_profilepage_label_label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label47, "Email : mukul.patient@gmail.com");

    ui_profilepage_label_label48 = lv_label_create(ui_screen_profilepage);
    lv_obj_set_width(ui_profilepage_label_label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label48, -25);
    lv_obj_set_y(ui_profilepage_label_label48, 101);
    lv_obj_set_align(ui_profilepage_label_label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label48, "Phone : 9999038799");

    ui_profilepage_label_label49 = lv_label_create(ui_screen_profilepage);
    lv_obj_set_width(ui_profilepage_label_label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label49, 1);
    lv_obj_set_y(ui_profilepage_label_label49, 125);
    lv_obj_set_align(ui_profilepage_label_label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label49, "Emergency No: 7009825401");

    lv_obj_add_event_cb(ui_profilepage_panel_backpannel4, ui_event_profilepage_panel_backpannel4, LV_EVENT_ALL, NULL);

}
