// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void ui_screen_wificonnectionpage1_screen_init(void)
{
    ui_screen_wificonnectionpage1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_wificonnectionpage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wificonnectionpage1_label_title = lv_label_create(ui_screen_wificonnectionpage1);
    lv_obj_set_width(ui_wificonnectionpage1_label_title, 163);
    lv_obj_set_height(ui_wificonnectionpage1_label_title, 40);
    lv_obj_set_y(ui_wificonnectionpage1_label_title, -28);
    lv_obj_set_x(ui_wificonnectionpage1_label_title, lv_pct(2));
    lv_obj_set_align(ui_wificonnectionpage1_label_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wificonnectionpage1_label_title, "Connecting...");
    lv_obj_set_style_text_font(ui_wificonnectionpage1_label_title, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wificonnectionpage1_label_status = lv_label_create(ui_screen_wificonnectionpage1);
    lv_obj_set_width(ui_wificonnectionpage1_label_status, 190);
    lv_obj_set_height(ui_wificonnectionpage1_label_status, 40);
    lv_obj_set_y(ui_wificonnectionpage1_label_status, 31);
    lv_obj_set_x(ui_wificonnectionpage1_label_status, lv_pct(6));
    lv_obj_set_align(ui_wificonnectionpage1_label_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wificonnectionpage1_label_status, "Disconnected");
    lv_obj_set_style_text_color(ui_wificonnectionpage1_label_status, lv_color_hex(0xFF0000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wificonnectionpage1_label_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wificonnectionpage1_label_status, &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wificonnectionpage1_label_statuserror = lv_label_create(ui_screen_wificonnectionpage1);
    lv_obj_set_width(ui_wificonnectionpage1_label_statuserror, 157);
    lv_obj_set_height(ui_wificonnectionpage1_label_statuserror, 15);
    lv_obj_set_x(ui_wificonnectionpage1_label_statuserror, 13);
    lv_obj_set_y(ui_wificonnectionpage1_label_statuserror, 51);
    lv_obj_set_align(ui_wificonnectionpage1_label_statuserror, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wificonnectionpage1_label_statuserror, "Failed to Connect ");
    lv_obj_set_style_text_color(ui_wificonnectionpage1_label_statuserror, lv_color_hex(0xE93232),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wificonnectionpage1_label_statuserror, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wificonnectionpage1_label_statuserror, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_screen_wificonnectionpage1, ui_event_screen_wificonnectionpage1, LV_EVENT_ALL, NULL);
    uic_Screen_wificonnectionpage1 = ui_screen_wificonnectionpage1;
    uic_wificonnectionpage1_Label_status = ui_wificonnectionpage1_label_status;
    uic_wificonnectionpage1_Label_statuserror = ui_wificonnectionpage1_label_statuserror;

}
