// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Smriti_UI

#include "ui.h"

void ui_screen_profilepage_screen_init(void)
{
    ui_screen_profilepage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_profilepage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_panel_backpannel4 = lv_obj_create(ui_screen_profilepage);
    lv_obj_set_width(ui_profilepage_panel_backpannel4, 188);
    lv_obj_set_height(ui_profilepage_panel_backpannel4, 50);
    lv_obj_set_x(ui_profilepage_panel_backpannel4, 2);
    lv_obj_set_y(ui_profilepage_panel_backpannel4, -101);
    lv_obj_set_align(ui_profilepage_panel_backpannel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_profilepage_panel_backpannel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_label_back4 = lv_label_create(ui_profilepage_panel_backpannel4);
    lv_obj_set_width(ui_profilepage_label_back4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_back4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_back4, 10);
    lv_obj_set_y(ui_profilepage_label_back4, 5);
    lv_obj_set_align(ui_profilepage_label_back4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_back4, "Back");

    ui_profilepage_image_image5 = lv_image_create(ui_profilepage_panel_backpannel4);
    lv_image_set_src(ui_profilepage_image_image5, &ui_img_img_back_png);
    lv_obj_set_width(ui_profilepage_image_image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_image_image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_image_image5, -27);
    lv_obj_set_y(ui_profilepage_image_image5, 5);
    lv_obj_set_align(ui_profilepage_image_image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_profilepage_image_image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_profilepage_image_image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilepage_label_label9 = lv_label_create(ui_screen_profilepage);
    lv_obj_set_width(ui_profilepage_label_label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profilepage_label_label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profilepage_label_label9, 0);
    lv_obj_set_y(ui_profilepage_label_label9, -61);
    lv_obj_set_align(ui_profilepage_label_label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profilepage_label_label9, "Profile Page");
    lv_obj_set_style_text_color(ui_profilepage_label_label9, lv_color_hex(0x00FF17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_profilepage_label_label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_profilepage_panel_backpannel4, ui_event_profilepage_panel_backpannel4, LV_EVENT_ALL, NULL);

}
